### ISSUE TITLE
Cl(3,1) squaring test

### ISSUE THREAD

**Issue by rolfik** [dprodanov/clifford#1]
Thank You for the package and good work.

I have defined Cl(3,1) and issued this command:
![image](https://cloud.githubusercontent.com/assets/4658651/16163583/7dc0fc3c-34da-11e6-848e-a44c6802ef19.png)

The result should be 0 instead of -2 e14:
(e1 - e4)^2 = e1^2 - e14 - e41 + e4^2 = 1 - e14 + e14 - 1 = 0  
Squaring the result again results in -4.

Marek

**Comment by dprodanov** [comment]
Please try the new bug-fixed release. The issue is caused by the commutativity of "*" and the internal reordering of products in Maxima.

**Comment by rolfik** [comment]
Thank You, it is OK now.
