### ISSUE TITLE
Custom base element indices or symbols

### ISSUE THREAD

**Issue by rolfik** [dprodanov/clifford#2]
It would be nice if we could use custom base element indices or symbols like in python ga:

Eg:
clifford([-1,1,1,1], "o,e_1,e_2,e_3")
would define hyperbolic (spacetime) algebra Cl(3,1) with custom base symbols o, e_1, e_2, e_3.

clifford([-1,1,1,1], e, "0,1,2,3")
would define hyperbolic (spacetime) algebra Cl(3,1) with custom base symbols e_0, e_1, e_2, e_3.

**Comment by dprodanov** [comment]
Unfortunately - not possible. Only 1 abstract symbol can be assigned.
