### ISSUE TITLE
failure of expand of symbolic clifford elements 

### ISSUE THREAD

**Issue by peeterjoot** [dprodanov/clifford#4]
Here's an example of a symbolic expression for which the clifford product does not properly distribute:
![screen shot 2017-01-08 at 9 49 50 pm](https://cloud.githubusercontent.com/assets/163208/21768224/81e91354-d646-11e6-967d-0f49ebac97f9.png)

**Comment by dprodanov** [comment]
Is the issue still present?

**Comment by peeterjoot** [comment]
I believe that the solution was the use of a function that declared the sine as a scalar grade.
