### ISSUE TITLE
Octonions

### ISSUE THREAD

**Issue by ChuckEastwood** [dprodanov/clifford#6]
mtable2(); has an entry of 1 instead of -1 when clifford(e,0,3) is generated.

I am aware the octonions are nonassociative and declaring dotassoc:false; changes mtable2(); output to symbolic form.  I am trying to work with a subset that is supposed to be associative and added one line in permsign:

permsign(arr):=block([k:0, len, s:1, ret:0 ] ,
	mode_declare([k, len], fixnum),
	if not listp(arr) then return (false),
	len:length(arr),
	if octonions=true and len=(2*ndim) then k:k+1,		/* cwe */

as well as adding the variable octonions and setting it true to change the last entry of mtable2().

Any thoughts on side effects in cliffsimpall or dotsimpc?  I have successfully proved PP=P for projectors.

**Comment by dprodanov** [comment]
![image](https://user-images.githubusercontent.com/1756473/76082757-5ac38c80-5fac-11ea-9d72-19576b65dbf8.png)
Which line?

**Comment by dprodanov** [comment]
I don't see an issue. 
e[1,2,3]. e[1,2,3]=1 is correct.
DP

**Comment by ChuckEastwood** [comment]
Not according to Kurosh in "General Algebra",1963, page 227 as well as many other sources.  e[i].e[i] should equal -1.

**Comment by ChuckEastwood** [comment]
My apologies, I assumed clifford(e,0,3) generated the octonions.  In the clifford_lecturenote.pdf the octonions are discussed and their construction is clarified.  CE

**Comment by dprodanov** [comment]
Dear,

I do not support octonions. They are non-associative.

DP
